version: '3'
services: 
    app: 
      container_name: tinyurlclone_ui
      image: node:12.16.0
      volumes:
        - ./:/app
      working_dir: /app 
      ports: 
        - '4200:4200' 
      command: bash -c "npm install && npm run start"